stages:
  - test

e2e-tests:
  stage: test
  image: cypress/included:14.3.0
  script:
    - set -e
    - echo "Installing dependencies and starting servers..."
    
    # Frontend setup
    - cd src/my-app
    - npm ci
    - npm start &
    - FRONT_PID=$!
    - cd ../..
    
    # Backend setup
    - cd src/my-app/src/backend
    - python3 -m pip install --no-cache-dir -r requirements.txt
    - python3 app.py &
    - BACK_PID=$!
    - cd ../../..
    
    # Wait for servers
    - npx wait-on http://localhost:3000 http://localhost:5000/ping
    
    # Run Cypress - 
    - cd src/my-app
    - CYPRESS_BASE_URL=http://localhost:3000 npx cypress run
    - cd ../..
    
    # Cleanup
    - kill $BACK_PID || echo "Backend already stopped"
    - kill $FRONT_PID || echo "Frontend already stopped"
    
  artifacts:
    when: always
    paths:
      - src/my-app/cypress/videos/
      - src/my-app/cypress/screenshots/
    expire_in: 1 week