cypress-run:
  image: cypress/included:14.1.0
  stage: test
  script:
    - echo "Starting Cypress test run"
    - npm ci
    - npm run start &
    - npx wait-on http://localhost:3000
    - npx cypress run
  variables:
    SHELL: /bin/bash   
  only:
    - main
    - clean-ci
    - new-branch
