image: cypress/included:14.1.0

stages:
  - test

cypress-run:
  stage: test
  script:
    - echo "Installing deps..."
    - cd src/my-app
    - npm ci
    - echo " Starting React app..."
    - npm run start &
    - echo "Waiting for app..."
    - npx wait-on http://localhost:3000
    - echo "Running Cypress..."
    - npx cypress run
  variables:
    SHELL: /bin/bash
  only:
    - main
    - clean-ci
    - new-branch
