stages:
  - test

e2e-tests:
  stage: test
  image: cypress/included:14.3.0
  script:
    - echo "Installing frontend dependencies"
    - cd src/my-app
    - npm ci

    - echo "Starting frontend"
    - npm start & 
    - FRONT_PID=$!
    - cd ../..

    - echo "Starting mock backend"
    - cd src/my-app/src/backend
    - pip3 install --user -r requirements.txt
    - python3 app.py &
    - BACK_PID=$!
    - cd ../../..

    - echo "Waiting for servers to be ready"
    - npx wait-on http://localhost:3000/login http://localhost:5000/ping

    - echo "Running Cypress tests"
    - cypress run

    - echo "Cleaning up"
    - kill $BACK_PID || echo "Backend already stopped"
    - kill $FRONT_PID || echo "Frontend already stopped"
  artifacts:
    when: always
    paths:
      - cypress/videos/
      - cypress/screenshots/
    expire_in: 1 week
