stages:
  - test

debug-job:
  stage: test
  script:
    - echo "CI pipeline is working!"
  only:
    - clean-ci

cypress-run:
  image: cypress/included:14.1.0
  stage: test 
  working_directory: src/my-app
  script:
    - npm ci
    - npm run start &
    - npx wait-on http://localhost:3000
    - npx cypress run
  only:
    - clean-ci
