stages:
  - test-frontend
  - test-backend
  - test-e2e

test-frontend:
  stage: test-frontend
  image: node:18
  script:
    - cd src/my-app
    - npm ci
    - npm run test -- --coverage
  artifacts:
    paths:
      - src/my-app/coverage/
    expire_in: 1 week

# Backend Unit + Integration Tests with Pytest
test-backend:
  stage: test-backend
  image: python:3.11
  before_script:
    - cd src/my-app/src/backend
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest tests/unit
    - pytest tests/integration
  artifacts:
    paths:
      - src/my-app/src/backend/.pytest_cache/
    expire_in: 1 week

# E2E Tests with Cypress
test-e2e:
  stage: test-e2e
  image: cypress/included:14.1.0
  services:
    - name: docker:dind
      alias: docker
  variables:
    CYPRESS_baseUrl: http://localhost:3000
  before_script:
    - apt-get update && apt-get install -y curl
    - cd src/my-app
    - npm ci
    - npm run start &     # Start React app
    - cd src/backend
    - pip install -r requirements.txt
    - python app.py &     # Start Flask app
    - sleep 15            # Wait for servers
  script:
    - cd ../../../..      # Back to project root
    - npx cypress run
  artifacts:
    when: always
    paths:
      - cypress/screenshots
      - cypress/videos
    expire_in: 1 week
