stages:
  - test

e2e-tests:
  stage: test
  image: cypress/included:14.3.0
  script:
    - chmod +x scripts/dev-ci.sh
    - ./scripts/dev-ci.sh
  artifacts:
    when: always
    paths:
      - cypress/videos/
      - cypress/screenshots/
    expire_in: 1 week
