image: cypress/included:14.1.0

stages:
  - test

cypress-run:
  stage: test
  before_script:
    - apt-get update && apt-get install -y python3 python3-pip
  script:
    - cd src/my-app
    - npm ci
    - npm run start &                     # Frontend
    - cd ../../Online_Job_Posting_Database
    - python3 app.py &                   # Backend
    - cd ../src/my-app
    - npx wait-on http://localhost:3000
    - npx cypress run
  only:
    - clean-ci
