image: cypress/included:14.1.0

stages:
  - test

cypress-run:
  stage: test
  script:
    - echo "Starting Flask backend..."
    - cd src/my-app/src/backend
    - python app.py &
    - cd ../../..

    - echo "Starting React frontend..."
    - cd src/my-app
    - npm ci
    - npm run start &
    - npx wait-on http://localhost:3000 http://localhost:5000

    - echo "Running Cypress tests..."
    - npx cypress run --config baseUrl=http://localhost:3000
  only:
    - main
    - clean-ci
    - new-branch