stages:
  - test-frontend
  - test-backend
  - test-e2e

# Frontend Unit Tests with React Scripts
test-frontend:
  stage: test-frontend
  image: node:18
  script:
    - cd src/my-app
    - npm ci
    - npm run test -- --coverage
  artifacts:
    paths:
      - src/my-app/coverage/
    expire_in: 1 week

# # Backend Unit + Integration Tests with Pytest
# test-backend:
#   stage: test-backend
#   image: python:3.11
#   variables:
#     PYTHONPATH: "$CI_PROJECT_DIR/src/my-app/src/backend"
#   before_script:
#     - cd src/my-app/src/backend
#     - pip install --upgrade pip
#     - pip install nltk==3.9.1
#     - pip install --no-build-isolation -r requirements.txt
#     - pip install pytest
#     - python -m spacy download en_core_web_sm 
#   script:
#     - pytest tests/unit
#     - pytest tests/integration
#   artifacts:
#     paths:
#       - src/my-app/src/backend/.pytest_cache/
#     expire_in: 1 week

# Cypress E2E Tests
test-e2e:
  stage: test-e2e
  image: cypress/included:14.1.0
  services:
    - name: docker:dind
      command: ["--tls=false"]
  privileged: true   # ✅ Move this here!
  variables:
    CYPRESS_baseUrl: http://localhost:3000
  before_script:
    - apt-get update && apt-get install -y curl
    - cd src/my-app
    - npm ci
    - npm run start &             
    - cd src/backend
    - pip install nltk==3.9.1
    - pip install --no-build-isolation -r requirements.txt
    - python app.py &             
    - sleep 30
  script:
    - cd src/my-app
    - npx cypress run --config baseUrl=$CYPRESS_baseUrl
  artifacts:
    when: always
    paths:
      - cypress/screenshots
      - cypress/videos
    expire_in: 1 week
