image: cypress/included:14.1.0

stages:
  - test

cypress-run:
  stage: test
  working_directory: src/my-app
  script:
    - npm ci
    - npm run start &             # Start React app
    - npx wait-on http://localhost:3000  # Wait until it's live
    - npx cypress run             # Run your e2e tests
  only:
    - main
    - clean-ci
    - new-branch
