stages:
  - test

cypress-run:
  image: cypress/included:14.1.0
  stage: test
  script:
    - npm ci
    - npx cypress run
  only:
    - main
    - new-branch
  artifacts:
    when: always
    paths:
      - cypress/screenshots/
      - cypress/videos/
