stages:
  - test

cypress-run:
  image: cypress/included:14.1.0
  stage: test
  script:
    - npm ci
    # 1. Start the React app in background
    - npm run start &
    # 2. Wait for the app to be up (need a "wait" tool)
    - npx wait-on http://localhost:3000
    # 3. Run Cypress
    - npx cypress run
  only:
    - main
    - new-branch
