stages:
  - test

cypress-run:
  image: cypress/included:14.1.0
  stage: test
  script:
    - npm install
    - npx cypress run --config-file cypress.config.js
  artifacts:
    when: always
    expire_in: 1 week  
    paths:
      - test-results/
      - cypress/screenshots/
      - cypress/videos/

  only:
    - main
    - new-branch

cache:
  key: npm-cache
  paths:
    - node_modules/

