stages:
  - test

cypress-run:
  image:
    name: cypress/included:14.1.0
    entrypoint: [""]   # <-- Forces a blank entrypoint
  stage: test
  script:
    - npm ci
    - npx cypress run
  only:
    - main
    - new-branch
