stages:
  - test

cypress-run:
  image: cypress/included:14.1.0
  stage: test
  script:
    - npm install
    - npx cypress run  # No need for --config-file if cypress.config.js is at root
  only:
    - main
    - new-branch
