image: mcr.microsoft.com/playwright:v1.38.0-focal  # Official Playwright image

stages:
  - test

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - npm install
    - npx playwright install --with-deps
    - npx playwright test  # Runs tests in headless mode
  artifacts:
    when: always
    paths:
      - test-results/
    expire_in: 1 day
