stages:
  - test

cypress-run:
  image: cypress/included:14.1.0
  stage: test
  script:
    - cd src/my-app
    - npm ci
    - npm run start &  
    - npx wait-on http://localhost:3000 
    - npx cypress run --config-file cypress.config.js 
